apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
data:
  prometheus-alert-rules.yaml: |-
    groups:
    - name: pod.rules
      rules:
      - alert: HighPodCounts
        expr: pod_count > 100
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High Pod Count Detected"
          description: "Pod count is greater than 100 for more than 5 minutes."
