apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: monitoring
data:
  prometheus-additional.yaml: |
    - job_name: 'kuberesourcesmonitor'
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: kuberesourcesmonitor-system
        - source_labels: [__meta_kubernetes_service_label_app]
          action: keep
          regex: kuberesourcesmonitor-metrics
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          action: keep
          regex: metrics
        - source_labels: [__address__, __meta_kubernetes_endpoint_port_name]
          action: replace
          target_label: __address__
          regex: (.+):.*;(metrics)
          replacement: ${1}:2112
