apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kuberesourcesmonitor-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kuberesourcesmonitor-metrics
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - kuberesourcesmonitor-system
