apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kuberesourcesmonitor'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: kuberesourcesmonitor
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics
          - source_labels: [__address__, __meta_kubernetes_endpoint_port_name]
            action: replace
            target_label: __address__
            regex: (.+):.*;(metrics)
            replacement: ${1}:2112
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval: 15s\n  evaluation_interval: 15s\n\nscrape_configs:\n  - job_name: 'prometheus'\n    static_configs:\n      - targets: ['localhost:9090']\n\n  - job_name: 'kuberesourcesmonitor'\n    kubernetes_sd_configs:\n      - role: endpoints\n    relabel_configs:\n      - source_labels: [__meta_kubernetes_service_label_app]\n        action: keep\n        regex: kuberesourcesmonitor\n      - source_labels: [__meta_kubernetes_endpoint_port_name]\n        action: keep\n        regex: metrics\n      - source_labels: [__address__, __meta_kubernetes_endpoint_port_name]\n        action: replace\n        target_label: __address__\n        regex: (.+):.*;(metrics)\n        replacement: ${1}:2112\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"prometheus-config","namespace":"monitoring"}}
  creationTimestamp: "2024-07-20T16:18:55Z"
  name: prometheus-config
  namespace: monitoring
  resourceVersion: "2437473"
  uid: 2d17fd99-cad6-43ca-ae41-9c1662cbc9ce
