apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kuberesourcesmonitor-service-monitor
  namespace: kuberesourcesmonitor-system
  labels:
    release: kube-prometheus-stack ## should match with meta.helm.sh/release-name of kubectl get prometheus -n monitoring -o yaml
spec:
  selector:
    matchLabels:
      app: kuberesourcesmonitor-metrics
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - kuberesourcesmonitor-system

