apiVersion: v1
kind: Service
metadata:
  name: kuberesourcesmonitor-metrics
  namespace: kuberesourcesmonitor-system
  labels:
    app: kuberesourcesmonitor-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2112" 
    prometheus.io/path: "/metrics" 
spec:
  ports:
    - port: 2112
      targetPort: 2112
      protocol: TCP
      name: metrics
  selector:
    control-plane: kuberesourcesmonitor-controller-manager
  type: ClusterIP

