apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kuberesourcesmonitors.monitor.example.com
spec:
  group: monitor.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                configMapName:
                  type: string
                interval:
                  type: string
                prometheusEndpoint:
                  type: string
            status:
              type: object
              properties:
                lastChecked:
                  type: string
                message:
                  type: string
  scope: Namespaced
  names:
    plural: kuberesourcesmonitors
    singular: kuberesourcesmonitor
    kind: KubeResourcesMonitor
    shortNames:
    - krm
