apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  - nodes
  - persistentvolumes
  - persistentvolumeclaims
  - events
  - replicationcontrollers
  - endpoints
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create  
  - update  
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - update  
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.example.com
  resources:
  - kuberesourcesmonitors
  - kuberesourcesmonitors/status
  - kuberesourcesmonitors/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
