apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberesourcesmonitor-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "monitor.example.com"
  resources:
  - resourcemonitors
  verbs:
  - get
  - list
  - watch
