apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitor.example.com"]
  resources: ["kuberesourcesmonitors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["monitor.example.com"]
  resources: ["kuberesourcesmonitors/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["monitor.example.com"]
  resources: ["kuberesourcesmonitors/finalizers"]
  verbs: ["update"]
