# permissions for end users to edit kuberesourcesmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kuberesourcesmonitor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kuberesourcesmonitor
    app.kubernetes.io/part-of: kuberesourcesmonitor
    app.kubernetes.io/managed-by: kustomize
  name: kuberesourcesmonitor-editor-role
rules:
- apiGroups:
  - monitor.example.com
  resources:
  - kuberesourcesmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.example.com
  resources:
  - kuberesourcesmonitors/status
  verbs:
  - get
