# rolebinding_leader_election.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace: kuberesourcesmonitor-system
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: kuberesourcesmonitor-system
roleRef:
  kind: Role
  name: leader-election-role
  apiGroup: rbac.authorization.k8s.io

