# role_controller.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kuberesourcesmonitor-system
  name: controller-manager-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "events"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["monitor.example.com"]
  resources: ["kuberesourcesmonitors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["monitor.example.com"]
  resources: ["kuberesourcesmonitors/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["monitor.example.com"]
  resources: ["kuberesourcesmonitors/finalizers"]
  verbs: ["update"]

