apiVersion: monitor.example.com/v1alpha1
kind: KubeResourcesMonitor
metadata:
  name: example-kuberesourcesmonitor
  namespace: kuberesourcesmonitor-system
spec:
  interval: "5m"  # Interval for collecting metrics
  prometheusEndpoint: "2112"  # Endpoint for Prometheus metrics
  configMapName: "kuberesourcesmonitor-config"  # Name of the ConfigMap containing metrics configuration
  deployments:
    - name: "busybox-deployment"
      namespace: "default"  # Specify the namespace of the deployment
      minReplicas: 2
      maxReplicas: 5
      scaleTimes:
        - startTime: "00:00"  # Time to start scaling
          endTime: "06:00"    # Time to end scaling
          replicas: 5         # Number of replicas during this time window
        - startTime: "06:00"
          endTime: "23:59"
          replicas: 2
    # - name: "example-deployment-2"
    #   minReplicas: 1
    #   maxReplicas: 4
    #   scaleTimes:
    #     - startTime: "01:00"
    #       endTime: "05:00"
    #       replicas: 4
    #     - startTime: "05:00"
    #       endTime: "24:00"
    #       replicas: 1
