apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kuberesourcesmonitor.fullname" . }}-manager-role
  namespace: {{ .Release.Namespace | default "kuberesourcesmonitor-system" }}
  labels:
    app.kubernetes.io/name: {{ include "kuberesourcesmonitor.name" . }}
    helm.sh/chart: {{ include "kuberesourcesmonitor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  - nodes
  - persistentvolumeclaims
  - events
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
  - create  # Add create permission for events
  - update  # Add update permission for events
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - update  # Add update permission for deployments
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.example.com
  resources:
  - kuberesourcesmonitors
  - kuberesourcesmonitors/status
  - kuberesourcesmonitors/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
