apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kuberesourcesmonitors.monitor.example.com
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  group: monitor.example.com
  names:
    kind: KubeResourcesMonitor
    listKind: KubeResourcesMonitorList
    plural: kuberesourcesmonitors
    singular: kuberesourcesmonitor
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              configMapName:
                type: string
              interval:
                type: string
              prometheusEndpoint:
                type: string
              deployments:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    minReplicas:
                      type: integer
                    maxReplicas:
                      type: integer
                    scaleTimes:
                      type: array
                      items:
                        type: object
                        properties:
                          startTime:
                            type: string
                          endTime:
                            type: string
                          replicas:
                            type: integer
            required:
              - deployments
