apiVersion: monitor.example.com/v1alpha1
kind: KubeResourcesMonitor
metadata:
  name: example-kuberesourcesmonitor
  namespace: {{ .Release.Namespace }}
spec:
  interval: "{{ .Values.customResource.interval }}"
  prometheusEndpoint: "{{ .Values.customResource.prometheusEndpoint }}"
  configMapName: "{{ .Values.customResource.configMapName }}"
  deployments:
    {{- range .Values.customResource.deployments }}
    - name: "{{ .name }}"
      namespace: "{{ .namespace }}"
      minReplicas: {{ .minReplicas }}
      maxReplicas: {{ .maxReplicas }}
      scaleTimes:
        {{- range .scaleTimes }}
        - startTime: "{{ .startTime }}"
          endTime: "{{ .endTime }}"
          replicas: {{ .replicas }}
        {{- end }}
    {{- end }}
  messageQueues:
    {{- range .Values.customResource.messageQueues }}
    - queueSecretName: "{{ .queueSecretName }}"
      queueSecretKey: "{{ .queueSecretKey }}"
      queueNamespace: "{{ .queueNamespace }}"  
      queueName: "{{ .queueName }}"
      deploymentName: "{{ .deploymentName }}"
      deploymentNamespace: "{{ .deploymentNamespace }}"
      thresholdMessages: {{ .thresholdMessages }}
      scaleUpReplicas: {{ .scaleUpReplicas }}
      scaleDownReplicas: {{ .scaleDownReplicas }}
    {{- end }}
