apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kuberesourcesmonitor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "kuberesourcesmonitor.name" . }}
    chart: {{ include "kuberesourcesmonitor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
