apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcemonitors.monitor.example.com
spec:
  group: monitor.example.com
  names:
    kind: ResourceMonitor
    listKind: ResourceMonitorList
    plural: resourcemonitors
    singular: resourcemonitor
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              interval:
                type: string

